[Superion][PFR] - Out-of-band PFR Secure update.
Root Cause:
    N/A

Solution/Change:
    [phosphor-software-manager]
        Implement support for PFRBMC, PFRHost, and PFRRot version purpose.
    [pfr-update]
        A script to upgrade the image file to the appropriate partition.
    [phosphor-dbus-interfaces]
        Add new version purposes for PFR.

Entry Test:
    Updating firmware via TFTP.
    curl -k -basic -u root:0penBmc -X POST https://{bmc IP}/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate -d '{"TransferProtocol":"TFTP","ImageURI":"{server IP/file path}" }'

    Updating firmware via the REST.
        Upload the signed image.
            curl -u root:0penBmc -k -H "X-Auth-Token: $token" -H "Content-Type:application/octet-stream" -X POST -T <image.tar.gz> https://{bmc_ip}/upload/image

            {
              "data": "9416c73f",    <- ver_id
              "message": "200 OK",
              "status": "ok"
            }
        Image activation.
            curl -u root:0penBmc -b cjar -k -H "Content-Type: application/json" -X PUT -d '{"data":"xyz.openbmc_project.Software.Activation.RequestedActivations.Active"}'https://{bmc_ip}/xyz/openbmc_project/software/9416c73f/attr/RequestedActivation

            {
              "data": null,
              "message": "200 OK",
              "status": "ok"
            }

Test log:
    Updating the BMC firmware
        pfr-update:
        Updating bmc-stg : mtd9...
        Erasing block: 509/509 (100%)
        Writing kb: 32527/32527 (100%)
        Verifying kb: 32527/32527 (100%)
        Contents of mtd9 and image-bmc-stg are the same.
        Waiting for the AST1060 to verify and upgrade image...

        BP0c00
        U-Boot 2019.04 (Sep 29 2022 - 10:40:37 +0000)
        SOC: AST2600-A3

    Updating the AST1060 firmware
        pfr-update:
        Updating bmc-stg : mtd11...
        Erasing block: 5/5 (100%)
        Writing kb: 301/301 (100%)
        Verifying kb: 301/301 (100%)
        Contents of mtd11 and image-pfr-stg are the same.
        Waiting for the AST1060 to verify and upgrade image...

        BP0c00
        U-Boot 2019.04 (Sep 29 2022 - 10:40:37 +0000)
        SOC: AST2600-A3

    Updating firmware with an incorrect image name
        (image name starting with image-*)
        pfr-update:
        ERROR: Unable to find the MTD partition for image-test-stg.

        (image name doesn't start with image-*)
        pfr-update:
        No images found for updating.